name: Test code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - name: Install pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Enter directory
        run: cd src

      - name: Run the tests
        run: python -m coverage run -m unittest discover

      - name: Generate coverage report
        run: python -m coverage html

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
